# 三峡乡旅游景点管理系统配置文件
# 包含数据库连接、文件上传、MyBatis和服务器配置

# Spring框架相关配置
spring:
  # 数据源配置 - MySQL数据库连接设置
  datasource:
    # MySQL数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL，连接到本地MySQL的sxx数据库
    url: jdbc:mysql://localhost/sxx
    # 数据库用户名
    username: hyl
    # 数据库密码（生产环境建议使用环境变量）
    password: Xsq20050709##

  # Servlet相关配置
  servlet:
    # 文件上传配置
    multipart:
      # 单个文件最大上传大小限制
      max-file-size: 10MB
      # 整个请求的最大大小限制
      max-request-size: 100MB

# MyBatis配置
mybatis:
  # MyBatis核心配置
  configuration:
    # 日志实现，使用标准输出打印SQL语句，便于开发调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启驼峰命名转换，false表示不转换
    # 数据库字段名和Java属性名保持一致
    map-underscore-to-camel-case: false

# 服务器配置
server:
  # 应用服务器端口号，默认8080
  port: 8080
