# 大湖镇旅游景点管理系统配置文件
# 包含数据库连接、文件上传、MyBatis和服务器配置

# Spring框架相关配置
spring:
  # 数据源配置 - MySQL数据库连接设置
  datasource:
    # MySQL数据库驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL，连接到服务器MySQL的sxx数据库
    # 添加连接参数优化远程连接
    url: ${DB_URL}
    # 数据库用户名
    username: ${DB_USERNAME}
    # 数据库密码（从环境变量获取）
    password: ${DB_PASSWORD}

    # HikariCP连接池配置 - 专门针对远程数据库优化
    hikari:
      # 连接池中允许的最小连接数
      minimum-idle: 5
      # 连接池中允许的最大连接数
      maximum-pool-size: 10
      # 自动提交事务
      auto-commit: true
      # 连接超时时间（30秒）
      connection-timeout: 30000
      # 连接在池中闲置的最长时间（10分钟）
      idle-timeout: 600000
      # 连接的最长生命周期（25分钟，短于MySQL的wait_timeout）
      max-lifetime: 1500000
      # 连接泄露检测阈值（60秒）
      leak-detection-threshold: 60000
      # 连接池名称
      pool-name: HikariCP-Tourist
      # 连接有效性检查超时（5秒）
      validation-timeout: 5000
      # 连接测试查询
      connection-test-query: SELECT 1

  # Servlet相关配置
  servlet:
    # 文件上传配置
    multipart:
      # 单个文件最大上传大小限制
      max-file-size: 10MB
      # 整个请求的最大大小限制
      max-request-size: 100MB

# MyBatis配置
mybatis:
  # MyBatis核心配置
  configuration:
    # 日志实现，使用标准输出打印SQL语句，便于开发调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 是否开启驼峰命名转换，false表示不转换
    # 数据库字段名和Java属性名保持一致
    map-underscore-to-camel-case: false

# 服务器配置
server:
  # 应用服务器端口号，默认8080
  port: 8080

# 图片资源管理配置
image:
  # OSS存储桶基础URL
  base-url: https://dhz-tourism-1329017069.cos.ap-guangzhou.myqcloud.com
  # CDN加速域名（可选）
  cdn-url:
  # 是否启用CDN
  cdn-enabled: false
  # 默认缓存时长（秒）
  default-cache-duration: 86400
  # 静态资源缓存时长（秒）
  static-cache-duration: 31536000
  # 用户头像缓存时长（秒）
  avatar-cache-duration: 3600
  # 是否启用URL指纹
  fingerprint-enabled: false

# 代理配置
proxy:
  # 代理白名单
  bypass:
    - localhost
    - 127.0.0.1

# 腾讯云COS配置
cos:
  secret-id: ${COS_SECRET_ID}
  secret-key: ${COS_SECRET_KEY}
  region: ap-guangzhou
  bucket-name: ${COS_BUCKET_NAME}

# 微信小程序配置
wechat:
  # 小程序AppID
  app-id: ${WECHAT_APP_ID}
  # 小程序AppSecret
  app-secret: ${WECHAT_APP_SECRET}
  # 微信API地址
  api-url: https://api.weixin.qq.com/sns/jscode2session
  # 请求超时时间（毫秒）
  timeout: 5000
  # 是否启用开发模式（true：返回虚拟数据，false：调用真实微信API）
  dev-mode: true
  # 开发环境虚拟用户数据
  dev-users:
    - openid: "dev_openid_001"
      unionid: "dev_unionid_001"
      nickname: "开发测试用户1"
      avatar: "../../../../avatar1.png"
    - openid: "dev_openid_002"
      unionid: "dev_unionid_002"
      nickname: "开发测试用户2"
      avatar: "../../../../avatar2.jng"
    - openid: "dev_openid_003"
      unionid: null
      nickname: "开发测试用户3"
      avatar: "../../../../avatar3.png"
